"""reversed cascade delete fir blogs upon user deletion

Revision ID: 1036a7e51844
Revises: 7347905b4bc9
Create Date: 2025-07-07 14:57:53.192534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1036a7e51844'
down_revision: Union[str, Sequence[str], None] = '7347905b4bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
